# Site settings
title: GALERI MOMEN 2.0
email: ""
description: "Story Gallery"
url: "http://farrachman.github.io"
baseurl: "/galerimomen2.0"
facebook_username: "zulfarr"
twitter_username: "zulfarr"
instagram_username: "farrachman"
github_username:  "farrachman"
deviantart_username: ""
flickr_username: "zulfarr"
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   farrachman
  avatar: avatar.png
  favicon: favicon.ico
  info: Tukang Foto yang Lebih Narsis dari Fotomodel

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "http://farrachman.github.io/photorama/gallery/"  
  - JOURNAL: "http://farrachman.github.io/photorama/journal/"
  - ABOUT: "http://farrachman.github.io/photorama/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
